version: '3.9'

services:
  bitcoin:
    image: bitcoin-debug:latest
    stdin_open: true # docker run -i
    tty: true
    environment:
      - USER
    ports:
      - 8333:8333
      - 18333:18333
      - 18443:18443
      - 18444:18444
      - 38333:38333
      - 38332:38332
    volumes:
      - ./bitcoin/:/bitcoin/
      - ./.data:${BITCOIN_DATA}
      - ./debug-configurations.json:/dev/.vscode/launch.json
      - ./build.sh:/build.sh
      - ./bitcoin.conf:/.bitcoin/bitcoin.conf
    command: /bin/bash